#!/usr/bin/env bash
# AUTHOR the HAllA environment: resolve current versions, install them, and write the locks.
#
# Run this by hand when you want to move versions — it is the only thing that changes what
# HAllA runs on. The image never runs this; it runs restore.sh, which installs exactly what
# the locks record. Two scripts so "works on my laptop" and "works in the image" are the
# same claim rather than two.
#
#   bash envs/halla/build.sh      # then commit the regenerated *.lock.txt
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$HERE/env.conf"

# --- Python side -------------------------------------------------------------------
if command -v uv >/dev/null 2>&1; then
  uv venv "$HERE/.venv" --python "$PYTHON_VERSION" --allow-existing
  VIRTUAL_ENV="$HERE/.venv" uv pip install -r "$HERE/requirements.txt"
  VIRTUAL_ENV="$HERE/.venv" uv pip freeze > "$HERE/requirements.lock.txt.new"
else
  python3 -m venv "$HERE/.venv"
  "$HERE/.venv/bin/pip" install -q --upgrade pip
  "$HERE/.venv/bin/pip" install -r "$HERE/requirements.txt"
  "$HERE/.venv/bin/pip" freeze > "$HERE/requirements.lock.txt.new"
fi
{
  echo "# GENERATED by envs/halla/build.sh — do not edit by hand."
  echo "# The exact Python environment HAllA runs in. restore.sh installs precisely this, so the"
  echo "# image and a laptop get the same interpreter contents. Re-generate by running build.sh."
  cat "$HERE/requirements.lock.txt.new"
} > "$HERE/requirements.lock.txt"
rm -f "$HERE/requirements.lock.txt.new"

# --- R side -----------------------------------------------------------------------
# HAllA is not pure Python: it calls R through rpy2 and imports XICOR and eva at module load
# (halla/utils/similarity.py, utils/stats.py), so the CLI cannot start without them. They go
# in a library dedicated to HAllA rather than the global R user library, so this env stays
# self-contained and nothing leaks into the system R that the r-stats renv project uses.
# A DATED CRAN snapshot is the pin: the same URL always resolves the same versions.
mkdir -p "$HERE/rlib"
Rscript -e "
  install.packages(strsplit('$R_PACKAGES', ' +')[[1]],
                   lib = '$HERE/rlib', repos = '$CRAN_SNAPSHOT', quiet = TRUE)
"
Rscript -e "
  ip <- installed.packages(lib.loc = '$HERE/rlib')[, 'Version']
  cat('# GENERATED by envs/halla/build.sh — do not edit by hand.\n')
  cat('# HAllA calls R through rpy2 and imports these at module load, so the CLI cannot\n')
  cat('# start without them. Versions are what the CRAN_SNAPSHOT in env.conf resolved to;\n')
  cat('# restore.sh re-installs from that same dated snapshot, which is the reproducibility.\n')
  for (n in sort(names(ip))) cat(sprintf('%s %s\n', n, ip[n]))
" > "$HERE/r-requirements.lock.txt"

bash "$HERE/verify.sh"
echo "halla env AUTHORED — commit the regenerated locks in $HERE"
