#!/usr/bin/env python3
"""
GEO Report Generator

Generate HTML report of GEO search results for easy browsing and sharing.
"""

import argparse
import json
import sys
from datetime import datetime
from pathlib import Path
from typing import List, Dict

from geo_search import GEOSearcher


HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>GEO Search Results - {query}</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
            max-width: 1400px;
            margin: 0 auto;
            padding: 20px;
            background-color: #f5f5f5;
        }}
        h1 {{
            color: #333;
            border-bottom: 3px solid #4CAF50;
            padding-bottom: 10px;
        }}
        .metadata {{
            background-color: #fff;
            padding: 15px;
            border-radius: 5px;
            margin-bottom: 20px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }}
        table {{
            width: 100%;
            border-collapse: collapse;
            background-color: #fff;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }}
        th {{
            background-color: #4CAF50;
            color: white;
            padding: 12px;
            text-align: left;
            position: sticky;
            top: 0;
            z-index: 10;
        }}
        td {{
            padding: 12px;
            border-bottom: 1px solid #ddd;
        }}
        tr:hover {{
            background-color: #f5f5f5;
        }}
        .geo-id {{
            font-weight: bold;
            color: #1976D2;
        }}
        .title {{
            color: #333;
            max-width: 500px;
        }}
        .tissue {{
            display: inline-block;
            padding: 4px 8px;
            background-color: #e3f2fd;
            border-radius: 3px;
            font-size: 0.9em;
        }}
        .organism {{
            display: inline-block;
            padding: 4px 8px;
            background-color: #f3e5f5;
            border-radius: 3px;
            font-size: 0.9em;
        }}
        .btn {{
            display: inline-block;
            padding: 6px 12px;
            background-color: #4CAF50;
            color: white;
            text-decoration: none;
            border-radius: 4px;
            font-size: 0.9em;
        }}
        .btn:hover {{
            background-color: #45a049;
        }}
        .btn-secondary {{
            background-color: #2196F3;
        }}
        .btn-secondary:hover {{
            background-color: #0b7dda;
        }}
        .footer {{
            margin-top: 30px;
            padding: 15px;
            text-align: center;
            color: #666;
            font-size: 0.9em;
        }}
        .status-validated {{
            color: #4CAF50;
            font-weight: bold;
        }}
        .status-available {{
            color: #FF9800;
        }}
        .status-not-local {{
            color: #999;
        }}
    </style>
</head>
<body>
    <h1>GEO Search Results: {query}</h1>
    
    <div class="metadata">
        <strong>Generated:</strong> {timestamp}<br>
        <strong>Organism Filter:</strong> {organism}<br>
        <strong>Results:</strong> {n_results} datasets
    </div>
    
    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>GEO ID</th>
                <th>Title</th>
                <th>Organism</th>
                <th>Tissue</th>
                <th>Type</th>
                <th>PubMed</th>
                <th>Local Status</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {rows}
        </tbody>
    </table>
    
    <div class="footer">
        Generated by TumorSPACE GEO Tool | <a href="https://www.ncbi.nlm.nih.gov/geo/">NCBI GEO Database</a>
    </div>
</body>
</html>
"""

ROW_TEMPLATE = """
            <tr>
                <td>{index}</td>
                <td class="geo-id">{geo_id}</td>
                <td class="title">{title}</td>
                <td><span class="organism">{organism}</span></td>
                <td><span class="tissue">{tissue}</span></td>
                <td>{entry_type}</td>
                <td>{pubmed}</td>
                <td class="{status_class}">{status}</td>
                <td>
                    <a href="{geo_url}" class="btn btn-secondary" target="_blank">View on GEO</a>
                    {download_cmd}
                </td>
            </tr>
"""


class GEOReportGenerator:
    """Generate HTML reports for GEO search results"""
    
    def __init__(self, workspace_root: Path = None):
        """Initialize report generator"""
        if workspace_root is None:
            workspace_root = Path(__file__).resolve()
            while workspace_root.parent != workspace_root:
                if (workspace_root / ".git").exists():
                    break
                workspace_root = workspace_root.parent
        
        self.workspace_root = Path(workspace_root)
        self.local_datasets_dir = self.workspace_root / "local" / "datasets"
    
    def generate(self, query: str, results: List[Dict], organism: str = "All", 
                output_path: Path = None) -> Path:
        """
        Generate HTML report from search results
        
        Args:
            query: Search query used
            results: List of result dictionaries
            organism: Organism filter used
            output_path: Optional output path (default: local/geo_search_results_{timestamp}.html)
        
        Returns:
            Path to generated HTML file
        """
        if output_path is None:
            timestamp_str = datetime.now().strftime("%Y%m%d_%H%M%S")
            output_path = self.workspace_root / "local" / f"geo_search_results_{timestamp_str}.html"
        
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        
        # Generate table rows
        rows_html = []
        for i, result in enumerate(results, 1):
            geo_id = result['geo_id']
            
            # Check local status
            local_status, status_class = self._check_local_status(geo_id)
            
            # Download command for copy-paste
            download_cmd = f'<code style="font-size:0.8em">python workflows/python/geo_tool.py download {geo_id}</code>'
            
            row_html = ROW_TEMPLATE.format(
                index=i,
                geo_id=geo_id,
                title=result['title'][:100] + ('...' if len(result['title']) > 100 else ''),
                organism=result['organism'],
                tissue=result['tissue'],
                entry_type=result['entry_type'],
                pubmed=result['pubmed_id'] if result['pubmed_id'] else '-',
                status=local_status,
                status_class=status_class,
                geo_url=result['geo_url'],
                download_cmd=download_cmd
            )
            rows_html.append(row_html)
        
        # Generate full HTML
        html = HTML_TEMPLATE.format(
            query=query,
            timestamp=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            organism=organism,
            n_results=len(results),
            rows="".join(rows_html)
        )
        
        # Write file
        with open(output_path, 'w') as f:
            f.write(html)
        
        print(f"[GEOReport] HTML report generated: {output_path}")
        return output_path
    
    def _check_local_status(self, geo_id: str) -> tuple:
        """Check if dataset exists locally and its status"""
        dataset_dir = self.local_datasets_dir / geo_id
        
        if not dataset_dir.exists():
            return "Not downloaded", "status-not-local"
        
        validation_report = dataset_dir / "VALIDATION_REPORT.txt"
        if validation_report.exists():
            with open(validation_report, 'r') as f:
                content = f.read()
                if "Status: PASS" in content:
                    return "✓ Validated", "status-validated"
                else:
                    return "⚠ Failed validation", "status-available"
        
        return "Downloaded (not validated)", "status-available"


def main():
    """Command-line interface"""
    parser = argparse.ArgumentParser(description="Generate HTML report of GEO search results")
    parser.add_argument("query", help="Search query")
    parser.add_argument("--max-results", type=int, default=50, help="Maximum results")
    parser.add_argument("--organism", choices=["Homo sapiens", "Mus musculus"], help="Filter by organism")
    parser.add_argument("--output", help="Output HTML file path")
    parser.add_argument("--open", action="store_true", help="Open in browser after generation")
    
    args = parser.parse_args()
    
    # Search GEO
    print(f"Searching GEO for: {args.query}")
    searcher = GEOSearcher()
    results = searcher.search(args.query, max_results=args.max_results, organism=args.organism)
    
    if not results:
        print("No results found.")
        sys.exit(1)
    
    # Generate report
    generator = GEOReportGenerator()
    output_path = generator.generate(
        query=args.query,
        results=results,
        organism=args.organism or "All",
        output_path=Path(args.output) if args.output else None
    )
    
    print(f"\nHTML report saved to: {output_path}")
    
    # Open in browser if requested
    if args.open:
        import webbrowser
        webbrowser.open(f"file://{output_path.absolute()}")
        print("Opened in browser")


if __name__ == "__main__":
    main()
