#!/bin/bash
set -e

# Add gotree binary to existing julia_1.11.sif container
# This creates a new sandbox, adds gotree + workflows, precompiles, then converts back to .sif

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Load HPC cluster profile (exports module names; falls back to .example defaults)
_HPC_PROFILE="${SCRIPT_DIR}/../config/hpc_profile.sh"
[[ -f "$_HPC_PROFILE" ]] || _HPC_PROFILE="${_HPC_PROFILE}.example"
# shellcheck disable=SC1090
source "$_HPC_PROFILE" && unset _HPC_PROFILE

# Load Singularity module
hpc_module_load MODULE_SINGULARITY
WORKSPACE_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
JULIA_SIF="$SCRIPT_DIR/julia_1.9.sif"
JULIA_SANDBOX="$SCRIPT_DIR/julia_1.9_sandbox"
JULIA_SIF_NEW="$SCRIPT_DIR/julia_1.9_with_gotree.sif"
GOTREE_BIN="$WORKSPACE_ROOT/bin/gotree"

echo "========================================"
echo "Adding gotree to Julia Container"
echo "========================================"
echo "Input:  $JULIA_SIF"
echo "Output: $JULIA_SIF_NEW"
echo "Binary: $GOTREE_BIN"
echo ""

# Verify gotree exists
if [ ! -f "$GOTREE_BIN" ]; then
    echo "ERROR: gotree binary not found at $GOTREE_BIN"
    exit 1
fi

# Remove old sandbox if exists
if [ -d "$JULIA_SANDBOX" ]; then
    echo "Removing old sandbox..."
    rm -rf "$JULIA_SANDBOX"
fi

# Convert .sif to sandbox
echo "Step 1: Converting .sif to sandbox..."
singularity build --sandbox "$JULIA_SANDBOX" "$JULIA_SIF"

# Set permissions on sandbox to ensure executability
echo "Setting permissions on sandbox..."
chmod -R +rx "$JULIA_SANDBOX"

# Copy gotree binary
echo ""
echo "Step 2: Adding gotree binary..."
cp "$GOTREE_BIN" "$JULIA_SANDBOX/usr/local/bin/gotree"
chmod +x "$JULIA_SANDBOX/usr/local/bin/gotree"

# Copy workflow scripts into container
echo ""
echo "Step 3: Copying workflow scripts..."
mkdir -p "$JULIA_SANDBOX/opt/workflows"
cp -r "$WORKSPACE_ROOT/workflows/tumorspace_core/julia" "$JULIA_SANDBOX/opt/workflows/"
echo "  Copied julia scripts: $(ls -1 $JULIA_SANDBOX/opt/workflows/julia/*.jl | wc -l) files"
echo "  (R scripts are bundled in tumorspace_r.sif, not the Julia container)"

# Create mount points and add libgomp
echo ""
echo "Step 4: Creating mount points and adding gotree dependencies..."
mkdir -p "$JULIA_SANDBOX/project" "$JULIA_SANDBOX/scratch" "$JULIA_SANDBOX/software" "$JULIA_SANDBOX/lib64"
cp /lib64/libgomp.so.1 "$JULIA_SANDBOX/lib64/"
echo "  Created mount points: /project, /scratch, /software"
echo "  Copied libgomp.so.1 to /lib64/"

# Precompile Julia packages
echo ""
echo "Step 5: Precompiling Julia packages (this takes 2-3 minutes)..."
# Note: Using /bin/sh instead of bash for POSIX compatibility
# --cleanenv prevents host environment variables from contaminating container
singularity exec --no-home --cleanenv --writable \
    --env JULIA_DEPOT_PATH=/opt/julia_depot \
    --env JULIA_CPU_TARGET=generic \
    "$JULIA_SANDBOX" /bin/sh -c '
    set -e
    export LD_LIBRARY_PATH=/lib64:$LD_LIBRARY_PATH
    cd /opt/workflows/julia
    echo "Running: julia --project=. -e \"using Pkg; Pkg.instantiate(); Pkg.precompile()\""
    julia --project=. -e "using Pkg; Pkg.instantiate(); Pkg.precompile()"
    echo "✓ Julia packages precompiled successfully"
'

# Test gotree
echo ""
echo "Step 6: Testing gotree in container..."
singularity exec --cleanenv "$JULIA_SANDBOX" sh -c 'export LD_LIBRARY_PATH=/lib64:$LD_LIBRARY_PATH && gotree version' || echo "(Expected error - gotree needs arguments)"

# Test workflows exist
echo ""
echo "Step 7: Verifying workflow scripts..."
singularity exec --cleanenv "$JULIA_SANDBOX" ls -lh /opt/workflows/julia/ | head -5

# Build new .sif
echo ""
echo "Step 8: Building new .sif..."
if [ -f "$JULIA_SIF_NEW" ]; then
    echo "Removing old $JULIA_SIF_NEW..."
    rm -f "$JULIA_SIF_NEW"
fi

singularity build "$JULIA_SIF_NEW" "$JULIA_SANDBOX"

# Clean up sandbox
echo ""
echo "Step 9: Cleaning up..."
rm -rf "$JULIA_SANDBOX"

echo ""
echo "========================================"
echo "Build Complete!"
echo "========================================"
echo "New container: $JULIA_SIF_NEW"
echo ""
echo "Test with:"
echo "  singularity exec $JULIA_SIF_NEW julia /opt/workflows/julia/phylo_tree_build.jl --help"
echo ""

# ── Update config/capabilities.sh ─────────────────────────────────────────────
_CAPS="${WORKSPACE_ROOT}/config/capabilities.sh"
if [ -f "$_CAPS" ]; then
    if grep -q "^TUMORSPACE_CONTAINER_AVAILABLE=" "$_CAPS"; then
        sed -i 's/^TUMORSPACE_CONTAINER_AVAILABLE=.*/TUMORSPACE_CONTAINER_AVAILABLE=true/' "$_CAPS"
    else
        echo "TUMORSPACE_CONTAINER_AVAILABLE=true" >> "$_CAPS"
    fi
    sed -i "s/^CAPABILITIES_GENERATED_AT=.*/CAPABILITIES_GENERATED_AT=\"$(date '+%Y-%m-%d %H:%M:%S')\"/" "$_CAPS"
else
    cat > "$_CAPS" << EOF
# Generated by add_gotree_to_julia.sh — re-run bash setup.sh for full detection
TUMORSPACE_CONTAINER_AVAILABLE=true
CAPABILITIES_GENERATED_AT="$(date '+%Y-%m-%d %H:%M:%S')"
EOF
fi
unset _CAPS
echo "  ✓ config/capabilities.sh updated (TUMORSPACE_CONTAINER_AVAILABLE=true)"
